apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomized-helm-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-helm
    spec:
      version: v1.0
      generate:
        command: [sh, -c]
        args:
          - |
            helm template $ARGOCD_APP_NAME --repo $HELM_REPO_URL --version $HELM_VERSION $HELM_CHART_NAME --namespace $ARGOCD_APP_NAMESPACE -f values.yaml |
            kustomize build
      discover:
        find:
          command: [sh, -c]
          args: ["find . -name kustomization.yaml -o -name Chart.yaml"]