apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: 5.9.5
    helm:
      releaseName: gitlab
      values: |
        global:
          hosts:
            domain: gitlab.conxtor.com
            gitlab:
              name: gitlab.conxtor.com
          initialRootPassword:
            secret: gitlab-root-password
            key: password
          ingress:
            enabled: true
            provider: traefik
            configureCertmanager: true
            annotations:
              kubernetes.io/ingress.class: traefik
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.tls: "true"
        certmanager:
          install: false
        certmanager-issuer:
          email: admin@conxtor.com
        nginx-ingress:
          enabled: false
        gitlab:
          webservice:
            ingress:
              enabled: true
              tls:
                enabled: true
                secretName: gitlab-tls
              annotations:
                kubernetes.io/ingress.class: traefik
                cert-manager.io/cluster-issuer: letsencrypt
          gitaly:
            pdb:
              apiVersion: policy/v1
          webservice:
            pdb:
              apiVersion: policy/v1
          sidekiq:
            pdb:
              apiVersion: policy/v1
          registry:
            pdb:
              apiVersion: policy/v1
          minio:
            pdb:
              apiVersion: policy/v1
          gitlab-shell:
            pdb:
              apiVersion: policy/v1
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true