apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.gitlab.io
    targetRevision: 5.9.5
    chart: gitlab
    helm:
      releaseName: gitlab
      values: |
        global:
          hosts:
            domain: gitlab.conxtor.com
            gitlab:
              name: gitlab.conxtor.com
          initialRootPassword:
            secret: gitlab-root-password
            key: password
          ingress:
            enabled: true
            provider: traefik
            configureCertmanager: true
            annotations:
              kubernetes.io/ingress.class: traefik
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.tls: "true"
        certmanager:
          install: false
        certmanager-issuer:
          email: admin@conxtor.com
        nginx-ingress:
          enabled: false
        gitlab:
          webservice:
            ingress:
              enabled: true
              tls:
                enabled: true
                secretName: gitlab-tls
              annotations:
                kubernetes.io/ingress.class: traefik
                cert-manager.io/cluster-issuer: letsencrypt
  - repoURL: file://./
    targetRevision: HEAD
    path: .
    kustomize:
      patches:
      - patch: |
          apiVersion: policy/v1
          kind: PodDisruptionBudget
        target:
          group: policy
          version: v1beta1
          kind: PodDisruptionBudget
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true