apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitlab-application.yaml

patches:
- path: pdb-patches.yaml
  target:
    kind: PodDisruptionBudget
    group: policy
    version: v1beta1
    name: gitlab-gitaly
- path: pdb-patches.yaml
  target:
    kind: PodDisruptionBudget
    group: policy
    version: v1beta1
    name: gitlab-sidekiq-all-in-1-v1
- path: pdb-patches.yaml
  target:
    kind: PodDisruptionBudget
    group: policy
    version: v1beta1
    name: gitlab-webservice-default
- path: pdb-patches.yaml
  target:
    kind: PodDisruptionBudget
    group: policy
    version: v1beta1
    name: gitlab-registry-v1
- path: pdb-patches.yaml
  target:
    kind: PodDisruptionBudget
    group: policy
    version: v1beta1
    name: gitlab-minio-v1
- path: pdb-patches.yaml
  target:
    kind: PodDisruptionBudget
    group: policy
    version: v1beta1
    name: gitlab-gitlab-shell