apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitlab-application.yaml

patchesStrategicMerge:
- pdb-patches.yaml

patches:
- patch: |-
    - op: replace
      path: /apiVersion
      value: policy/v1
  target:
    group: policy
    version: v1beta1
    kind: PodDisruptionBudget