apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitlab-application.yaml

patches:
- patch: |
    apiVersion: policy/v1
    kind: PodDisruptionBudget
  target:
    group: policy
    version: v1beta1
    kind: PodDisruptionBudget