apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitlab-gitaly
  namespace: gitlab
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitlab-sidekiq-all-in-1-v1
  namespace: gitlab
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitlab-webservice-default
  namespace: gitlab
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitlab-registry-v1
  namespace: gitlab
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitlab-minio-v1
  namespace: gitlab
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitlab-gitlab-shell
  namespace: gitlab